databases:
  - name: socialmedia
    databaseName: socialmedia_9tgk
    user: socialmedia_9tgk_user

services:
  - type: web
    name: socialmedia
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: socialmedia
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false